### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by ntsimerekis** [WheeledParasite/NRF24_Chat#1]
I wanted to use this library for the project:

https://circuitpython-nrf24l01.readthedocs.io

It's very similar to the TMRh20 library you posted and even has compatibility with it. This library has good raspberry pi support, good examples, and good python documentation. If we are using python, I think we should use it. Although it doesn't matter too much, they are almost the same.

Also, we're using python for this right? I could use C++, I looked at the examples on the TMRh20, and it doesn't look too different from what I already know from C. But I don't have that much/any experience with C++. I also think that Python will be better in the long run for debugging. If you already know a bit of C++ I'm sure you'll pick up python pretty fast.

**Comment by gururise** [comment]
Hey guys, this library looks like a good one.  I don't see any problem with using it.  Though, it seems to require the Adafruit_Blinka library to emulate circuitpython on the Raspberry pi.

Seems like a good idea to use this library, that way, if you decide to move off the raspberry pi in the future, to build a small hand-held communicator using an ESP32 or Raspberry Pi Pico, you can do so easily.

**Comment by hunterDRuebsamen** [comment]
README has been updated to reflect new library.  Python is the main programming language.
